language: python

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

python:
   - 2.7

before_install:
   - sudo apt-get install libhdf5-serial-dev libnetcdf-dev
   - pip install -r requirements.txt
   - pip install nose

install:
   - pip install .

script:
   - nosetests --exe sids
