language: python

notifications:
  email:
     recipients:
       - nickpapior@gmail.com
     on_failure: always
     on_success: change

python:
  - 2.7

before_install:
  - sudo apt-get -qq install libhdf5-serial-dev libnetcdf-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
# The next couple lines fix a crash with multiprocessing on 
# Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt

install:
  - python setup.py install

script:
  - nosetests --exe sids
