language: python

branches:
  except:
  - /.*gh-pages.*/

sudo: false

notifications:
  email:
     recipients:
       - nickpapior@gmail.com
     on_failure: always
     on_success: change
  webhooks:
     urls:
       - https://webhooks.gitter.im/e/fa6dc002908da5678b5f
     on_success: change
     on_failure: always
     on_start: never

matrix:
  include:
   - python: 2.7
     env: COVERAGE=true
   - python: 2.7
     env: PYTHONOPTIMIZE=0
   - python: 2.7
     env: PYTHONOPTIMIZE=1
   - python: 2.7
     env: PYTHONOPTIMIZE=2
   - python: 3.5
     env: COVERAGE=true
   - python: 3.6
   

install:
  - conda install hdf4 libnetcdf
  - if [[ ${COVERAGE:-false} != false ]]; then
       pip install coverage codacy-coverage ;
    fi
  - pip install pytest pytest-cov
  - python setup.py install

script:
  - if [[ ${COVERAGE:-false} != false ]]; then
        pip install -e . ;
        pytest --cov=sisl ;
    else
        pytest --pyargs sisl ;
    fi

after_success:
  - if [[ ${COVERAGE:-false} != false ]]; then
       bash <(curl -s https://codecov.io/bash) ;
       coverage xml ;
       python-codacy-coverage -r coverage.xml ;
    fi


#
# These are setup scripts:
#

addons:
  apt:
    packages: &common_packages
      - gcc
      - gfortran
#      - libhdf5-serial-dev 
#      - libnetcdf-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh ;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh -O miniconda.sh ;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
# Do actual package installations
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-environment
