package:
  name: sisl
  version: 0.7.13

build:
  number: 1

requirements:
  run:
    - python
    - six
    - setuptools
    - numpy >=1.9
    - scipy
    - netCDF4

test:
  requires:
    - nose
    
about:
  home: https://zerothi.github.io/sisl/
  license: LGPL-3.0
  summary: 'Manipulating input/output files of DFT codes and simple tight-binding Hamiltonians.'