{% set TAG = environ.get('GIT_DESCRIBE_TAG', '')|replace('v', '') %}
{% set N = environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
  name: sisl-dev
  version: {{TAG}}

source:
  git_url: ../
  git_depth: 5

build:
  number: {{N}}

requirements:
  build:
    - python
    - six
    - setuptools
    - numpy >=1.9
    - scipy
    - netcdf4
  run:
    - python
    - six
    - numpy >=1.9
    - scipy
    - netcdf4
    
about:
  home: http://github.com/zerothi/sisl/
  author: Nick R. Papior
  license: LGPL-3.0
  summary: 'This is the development version of the sisl package, this will be updated more frequently'
