name: sisl_docs
dependencies:
  - python=3.5
  - gcc
  - numpy
  - scipy
  - netCDF4
  - matplotlib
  - sphinx_rtd_theme
  - numpydoc
  - jinja2
  - tornado
  - nbformat
  - jupyter_client
  - ipykernel
  - pip:
    - tqdm
    - sphinx
    - nbsphinx
    - send2Trash
